"""add format and scope to competitions

Revision ID: 51b29850782c
Revises: 
Create Date: 2026-07-20 23:33:24.353439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b29850782c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('health_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_health_groups_id'), 'health_groups', ['id'], unique=False)
    op.create_table('social_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_social_statuses_id'), 'social_statuses', ['id'], unique=False)
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=False)
    op.create_table('event_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_categories_id'), 'event_categories', ['id'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('template_file_path', sa.String(length=255), nullable=False),
    sa.Column('template_file_name', sa.String(length=100), nullable=False),
    sa.Column('template_type', sa.String(length=10), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.Enum('API', 'WEB', 'MOBILE', 'IMPORT', 'SYSTEM', name='auditsource'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_college_id', 'audit_logs', ['college_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_field_name', 'audit_logs', ['field_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('curators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_curators_id'), 'curators', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='notificationpriority'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_graduated', sa.Boolean(), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=True),
    sa.Column('personal_number', sa.String(length=6), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('enrollment_order_data', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('citizenship', sa.String(length=100), nullable=True),
    sa.Column('passport_series', sa.String(length=10), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('passport_issue_date', sa.Date(), nullable=True),
    sa.Column('passport_issued_by', sa.String(length=255), nullable=True),
    sa.Column('passport_department_code', sa.String(length=20), nullable=True),
    sa.Column('registration_region', sa.String(length=100), nullable=True),
    sa.Column('registration_city', sa.String(length=100), nullable=False),
    sa.Column('registration_street', sa.String(length=200), nullable=True),
    sa.Column('registration_house', sa.String(length=20), nullable=True),
    sa.Column('registration_apartment', sa.String(length=10), nullable=True),
    sa.Column('registration_zip', sa.String(length=10), nullable=True),
    sa.Column('actual_region', sa.String(length=100), nullable=True),
    sa.Column('actual_city', sa.String(length=100), nullable=False),
    sa.Column('actual_street', sa.String(length=200), nullable=True),
    sa.Column('actual_house', sa.String(length=20), nullable=True),
    sa.Column('actual_apartment', sa.String(length=10), nullable=True),
    sa.Column('actual_zip', sa.String(length=10), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('snils', sa.String(length=14), nullable=True),
    sa.Column('medical_policy', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('health_group_id', sa.Integer(), nullable=True),
    sa.Column('social_status_id', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('disability_group', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['health_group_id'], ['health_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_status_id'], ['social_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_academic_year_id', 'students', ['academic_year_id'], unique=False)
    op.create_index('ix_students_actual_city', 'students', ['actual_city'], unique=False)
    op.create_index('ix_students_birth_date', 'students', ['birth_date'], unique=False)
    op.create_index('ix_students_college_id', 'students', ['college_id'], unique=False)
    op.create_index('ix_students_gender', 'students', ['gender'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index('ix_students_is_active', 'students', ['is_active'], unique=False)
    op.create_index('ix_students_is_graduated', 'students', ['is_graduated'], unique=False)
    op.create_index('ix_students_personal_number', 'students', ['personal_number'], unique=False)
    op.create_index('ix_students_registration_city', 'students', ['registration_city'], unique=False)
    op.create_index('ix_students_social_status_id', 'students', ['social_status_id'], unique=False)
    op.create_index('ix_students_user_id', 'students', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competition_date', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('OFFLINE', 'ONLINE', name='competitionformat'), nullable=False),
    sa.Column('scope', sa.Enum('INTERNAL', 'CITY', 'REGIONAL', 'OBLAST', 'INTERREGIONAL', 'NATIONAL', 'INTERNATIONAL', name='competitionscope'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitions_academic_year_id', 'competitions', ['academic_year_id'], unique=False)
    op.create_index('ix_competitions_college_id', 'competitions', ['college_id'], unique=False)
    op.create_index('ix_competitions_competition_date', 'competitions', ['competition_date'], unique=False)
    op.create_index('ix_competitions_curator_id', 'competitions', ['curator_id'], unique=False)
    op.create_index('ix_competitions_format', 'competitions', ['format'], unique=False)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index('ix_competitions_scope', 'competitions', ['scope'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('event_type', sa.Enum('MEETING', 'LECTURE', 'EXAM', 'HOLIDAY', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_type', sa.Enum('WEEKLY', 'MONTHLY', name='recurrencetype'), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_academic_year_id', 'events', ['academic_year_id'], unique=False)
    op.create_index('ix_events_category_id', 'events', ['category_id'], unique=False)
    op.create_index('ix_events_college_id', 'events', ['college_id'], unique=False)
    op.create_index('ix_events_curator_id', 'events', ['curator_id'], unique=False)
    op.create_index('ix_events_event_date', 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('work_place', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index('ix_family_members_student_id', 'family_members', ['student_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.Enum('PDF', 'JPG', 'JPEG', 'PNG', 'DOCX', 'XLSX', 'CSV', name='filetype'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('student_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievement_date', sa.Date(), nullable=False),
    sa.Column('achievement_type', sa.Enum('SPORT', 'ACADEMIC', 'CREATIVE', 'OTHER', name='achievementtype'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'JPG', 'JPEG', 'PNG', 'DOCX', 'XLSX', 'CSV', name='filetype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_achievements_achievement_date', 'student_achievements', ['achievement_date'], unique=False)
    op.create_index(op.f('ix_student_achievements_id'), 'student_achievements', ['id'], unique=False)
    op.create_index('ix_student_achievements_student_id', 'student_achievements', ['student_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'JPG', 'JPEG', 'PNG', 'DOCX', 'XLSX', 'CSV', name='filetype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_documents_document_type_id', 'student_documents', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_index('ix_student_documents_student_id', 'student_documents', ['student_id'], unique=False)
    op.create_table('competition_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.Enum('VICTORY', 'PRIZE', 'PARTICIPATION', 'DIPLOMA', name='competitionresulttype'), nullable=True),
    sa.Column('result_description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'JPG', 'JPEG', 'PNG', 'DOCX', 'XLSX', 'CSV', name='filetype'), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comp_participants_competition_id', 'competition_participants', ['competition_id'], unique=False)
    op.create_index('ix_comp_participants_student_id', 'competition_participants', ['student_id'], unique=False)
    op.create_index(op.f('ix_competition_participants_id'), 'competition_participants', ['id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_participants_event_id', 'event_participants', ['event_id'], unique=False)
    op.create_index('ix_event_participants_group_id', 'event_participants', ['group_id'], unique=False)
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_index('ix_event_participants_student_id', 'event_participants', ['student_id'], unique=False)
    op.create_table('group_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_students_group_id', 'group_students', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_students_id'), 'group_students', ['id'], unique=False)
    op.create_index('ix_group_students_is_active', 'group_students', ['is_active'], unique=False)
    op.create_index('ix_group_students_student_id', 'group_students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_students_student_id', table_name='group_students')
    op.drop_index('ix_group_students_is_active', table_name='group_students')
    op.drop_index(op.f('ix_group_students_id'), table_name='group_students')
    op.drop_index('ix_group_students_group_id', table_name='group_students')
    op.drop_table('group_students')
    op.drop_index('ix_event_participants_student_id', table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_index('ix_event_participants_group_id', table_name='event_participants')
    op.drop_index('ix_event_participants_event_id', table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_competition_participants_id'), table_name='competition_participants')
    op.drop_index('ix_comp_participants_student_id', table_name='competition_participants')
    op.drop_index('ix_comp_participants_competition_id', table_name='competition_participants')
    op.drop_table('competition_participants')
    op.drop_index('ix_student_documents_student_id', table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_index('ix_student_documents_document_type_id', table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index('ix_student_achievements_student_id', table_name='student_achievements')
    op.drop_index(op.f('ix_student_achievements_id'), table_name='student_achievements')
    op.drop_index('ix_student_achievements_achievement_date', table_name='student_achievements')
    op.drop_table('student_achievements')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('ix_family_members_student_id', table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_events_event_date', table_name='events')
    op.drop_index('ix_events_curator_id', table_name='events')
    op.drop_index('ix_events_college_id', table_name='events')
    op.drop_index('ix_events_category_id', table_name='events')
    op.drop_index('ix_events_academic_year_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_competitions_scope', table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_index('ix_competitions_format', table_name='competitions')
    op.drop_index('ix_competitions_curator_id', table_name='competitions')
    op.drop_index('ix_competitions_competition_date', table_name='competitions')
    op.drop_index('ix_competitions_college_id', table_name='competitions')
    op.drop_index('ix_competitions_academic_year_id', table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('ix_students_user_id', table_name='students')
    op.drop_index('ix_students_social_status_id', table_name='students')
    op.drop_index('ix_students_registration_city', table_name='students')
    op.drop_index('ix_students_personal_number', table_name='students')
    op.drop_index('ix_students_is_graduated', table_name='students')
    op.drop_index('ix_students_is_active', table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index('ix_students_gender', table_name='students')
    op.drop_index('ix_students_college_id', table_name='students')
    op.drop_index('ix_students_birth_date', table_name='students')
    op.drop_index('ix_students_actual_city', table_name='students')
    op.drop_index('ix_students_academic_year_id', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_curators_id'), table_name='curators')
    op.drop_table('curators')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_field_name', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_college_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_event_categories_id'), table_name='event_categories')
    op.drop_table('event_categories')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_social_statuses_id'), table_name='social_statuses')
    op.drop_table('social_statuses')
    op.drop_index(op.f('ix_health_groups_id'), table_name='health_groups')
    op.drop_table('health_groups')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
