"""fresh_start

Revision ID: 787a86d377c6
Revises: 
Create Date: 2026-07-23 19:16:01.657028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787a86d377c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Создаём таблицу specialties (без college_id)
    op.create_table(
        'specialties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=15), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    op.create_index('ix_specialties_id', 'specialties', ['id'])
    op.create_index('ix_specialties_code', 'specialties', ['code'], unique=True)

    # 2. Добавляем колонку college_id с DEFAULT (временным значением)
    op.add_column('specialties', sa.Column('college_id', sa.Integer(), nullable=False, server_default='1'))
    
    # 3. Добавляем внешний ключ
    op.create_foreign_key(
        'fk_specialties_college_id',
        'specialties',
        'colleges',
        ['college_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # 4. Убираем DEFAULT (после того как все записи получили college_id)
    op.alter_column('specialties', 'college_id', server_default=None)

    # 5. Добавляем колонку specialty_id в groups
    op.add_column('groups', sa.Column('specialty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_groups_specialty_id',
        'groups',
        'specialties',
        ['specialty_id'],
        ['id'],
        ondelete='SET NULL'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_personal_number'), table_name='students')
    op.create_index('ix_students_personal_number', 'students', ['personal_number'], unique=False)
    op.drop_constraint(None, 'specialties', type_='foreignkey')
    op.create_unique_constraint('specialties_code_key', 'specialties', ['code'])
    op.drop_column('specialties', 'college_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_college_id_fkey', 'groups', 'colleges', ['college_id'], ['id'])
    # ### end Alembic commands ###
